### ISSUE TITLE
How many disk storages are needed for storing the hdf5 files?

### ISSUE THREAD

**Issue by mutianxu** [facebookresearch/ic_gan#36]
Dear authors,

Thanks for your great work!

When I was running the data preparation for generating hdf5 files of 256*256 ImageNet, I got the error of:

"numpy.core._exceptions.MemoryError: Unable to allocate 11.9 TiB for an array with shape (1281167, 1281167)".

So I was wondering about how many disk spaces are needed for generating hdf5 files of **256*256 ImageNet**?

Looking forward to your reply!

Thanks a lot!

**Comment by ArantxaCasanova** [comment]
Hello,

thank you for your appreciation!

Could you specify which script is running when this error appears? It seems to me that this is a RAM error due to the nearest neighbor computation in `make_hdf5_nns.py`. I ran `make_hdf5_nns.py` with 8 GPUs available. If that is not an option, you may consider re-writing the [function](https://github.com/facebookresearch/ic_gan/blob/8eff2f7390e385e801993211a941f3592c50984d/data_utils/datasets_common.py#L695)  that computes the nearest neighbors using faiss.

Right now, the pairwise distances are computed with all datapoints at the same time (1.2M x 1.2M). In order to break it down in smaller batches with your specified `knn_batch_size`, you could replace [this line](https://github.com/facebookresearch/ic_gan/blob/8eff2f7390e385e801993211a941f3592c50984d/data_utils/datasets_common.py#L727) by a piece of code resembling the following block:
```
 kth_values_arg = []
 for xq in matrix_iterator(0, len(self.feats), knn_batch_size):
        _, kth_values_arg_ = knn_ground_truth(
            xq, matrix_iterator(0,len(self.feats), knn_batch_size), k_nn
        )
        kth_values_arg.append(kth_values_arg_)

kth_values_arg = np.vstack(kth_values_arg)

```
`kth_values` is not a used variable so it does not matter what it contains. The important one is `kth_values_arg`, which actually contains the indexes of the neighbors for each sample with shape (1281167, k_nn).


Using the variable `root_feats` in [here](https://github.com/facebookresearch/ic_gan/blob/8eff2f7390e385e801993211a941f3592c50984d/data_utils/datasets_common.py#L422) that will need to be stored as `self.root_feats_file = root_feats` in the `init` function. This will load the features gradually by batches with the new function `matrix_iterator` :
You will also need to import and define the following:
```
from faiss.contrib.exhaustive_search import knn_ground_truth

def matrix_iterator(ini, end, bs):
    for i0 in trange(ini, end, bs):
        with h5.File(self.root_feats_file, "r") as f:
            all_feats = f["feats"][i0 : i0 + bs]
            all_feats /= np.linalg.norm(all_feats, axis=-1, keepdims=True)
        yield all_feats.astype("float32")
```

**Comment by mutianxu** [comment]
Dear authors,

Thanks for your quick reply!

I noticed that the major problem is that I forgot to install the **faiss** package, so that in your code, it will not import faiss and directly uses sklearn to compute knn as specified [here](https://github.com/facebookresearch/ic_gan/blob/8eff2f7390e385e801993211a941f3592c50984d/data_utils/datasets_common.py#L733) in your code. 

After installing faiss, the knn computation will be paralleled on multiple gpus. This solves my problem!

BTW, I personally think that most computers can not compute knn directly using sklearn due to the huge memory usage, so it would be better if you could make some changes or specifications here.

Thanks a lot for your kind assistance!
